### ISSUE TITLE
Have conflict with setDefaultUncaughtExceptionHandler

### ISSUE THREAD

**Issue by dotfeng** [iqiyi/xCrash#1]
Have conflict with setDefaultUncaughtExceptionHandler() ?

**Comment by caikelun** [comment]
No. You can set your own `UncaughtExceptionHandler` before or after xCrash Initialized. Try to search `defaultHandler` in https://github.com/iqiyi/xCrash/blob/master/src/java/xcrash/xcrash_lib/src/main/java/xcrash/JavaCrashHandler.java

Or you can disable the Java exception capture mechanism separately by `InitParameters.disableJavaCrashHandler()`.

**Comment by dotfeng** [comment]
Thank you.
