### ISSUE TITLE
你好，请教一个编译问题lzma

### ISSUE THREAD

**Issue by fvaryu** [iqiyi/xCrash#10]
因为android.mk不熟，我把项目转成了cmake，但是编译的时候包如下错误。

libxcrash_dumper/lzma/./Threads.h:18:9: error: unknown type name 'HANDLE'
typedef HANDLE CThread;
        ^

说HANDLE找不到，搜索确实没有，不知道为什么。我下载lzma的代码也不行。

macos
as3.4.1
ndk最新的

**Comment by fvaryu** [comment]
已解决：添加编译条件 -Wall -Wextra -Werror -Wno-enum-conversion -fPIC -D_7ZIP_ST

-fPIC更换掉了原来的-fPIE 虽然不懂是什么意思，编译器提示的。

**Comment by caikelun** [comment]
🍻

**Comment by caikelun** [comment]
@fvaryu 改为 `-fPIC` 是有问题的，libxcrash_dumper 是个可执行文件，需要在编译时加 `-fPIE`，链接时加 `-pie`。

**Comment by eksea** [comment]
> -D_7ZIP_ST

你加了-D_7ZIP_ST，编单线程lzma就不会用到HANDLE
