### ISSUE TITLE
通过线程名获取java堆栈

### ISSUE THREAD

**Issue by StephenNeverMore** [iqiyi/xCrash#13]
![image](https://user-images.githubusercontent.com/11781922/60934826-50a49d80-a2fa-11e9-82eb-4a6ab068b720.png)
想了解下目前你们线上的数据情况，获取java堆栈失败的情况占多少？如果两个线程名类似（例如线程池默认的名字）应该会上报两个Thread的java堆栈了吧

**Comment by caikelun** [comment]
这个没有统计过。我们自己app线程基本都有明确名字的。这里用线程名判断是不严谨的，后续会考虑优化下。

**Comment by caikelun** [comment]
@StephenNeverMore 2.4.0 版本中，在 API level >= 21 （安卓 5.x 及以上版本中）已经使用了可靠的方法来获取崩溃线程的java stacktrace。

**Comment by StephenNeverMore** [comment]
> @StephenNeverMore 2.4.0 版本中，在 API level >= 21 （安卓 5.x 及以上版本中）已经使用了可靠的方法来获取崩溃线程的java stacktrace。

赞赞👍
