### ISSUE TITLE
有ANR异常捕获吗

### ISSUE THREAD

**Issue by WMHbear** [iqiyi/xCrash#14]
ANR异常捕获应该还比较好获得的吧，这个功能在Xcrash上支持吗

**Comment by caikelun** [comment]
ANR捕获目前还没有，我们会尽快加入的。

**Comment by caikelun** [comment]
@WMHbear 2.4.0 版本中包含了 ANR 捕获功能。

**Comment by imknown** [comment]
试了一下 确实可以在 `data/data/..` 生成自己的日志, 但是 会入侵系统 的 `/data/anr`, 导致系统生成的 ANR 不准.

**Comment by WMHbear** [comment]
good  job!

**Comment by caikelun** [comment]
@imknown 是的，是会有这个问题，毕竟在 sigquit 后是 xCrash 先做了捕获和dump的事情。

刚发了 2.4.1 版本，现在 xCrash 处理完 ANR 之后，会重发一个 sigquit 给 ART，让 ART 也能生成 traces。
