### ISSUE TITLE
可以不使用dumper么？

### ISSUE THREAD

**Issue by LiangChaoPossible** [iqiyi/xCrash#15]
如果不使用dumper，直接通过xc_fallback_get_emergency 会有什么区别么？
xc_fallback_get_emergency会有数据不全，或者信息不全的问题么？

**Comment by caikelun** [comment]
fallback是在崩溃线程自身的signal handler中执行的，稳定性比较低。dumper是个独立进程，充当gdb的角色，可以比较可靠的“调试”已崩溃的进程。

**Comment by LiangChaoPossible** [comment]
稳定性比较低，是指信息收集还没执行完，进程就会退出么？还是说崩溃信息收集不全。

**Comment by caikelun** [comment]
是的，信息收集没有完成就可能会退出。

崩溃进程可能已经fd耗尽、虚拟内存空间耗尽等，因此在崩溃进程中执行收集信息的逻辑，会有很多问题。

signal handler中也有很多额外的限制，参考：http://man7.org/linux/man-pages/man7/signal-safety.7.html

**Comment by LiangChaoPossible** [comment]
谢谢。

**Comment by LiangChaoPossible** [comment]
执行build.sh对环境有要求么？我用mac执行，会报很多undeclared的错误，比如：
error: 'SYS_close' undeclared (first use in this function)
error: 'F_SETPIPE_SZ' undeclared 
error: 'PR_SET_PTRACER' undeclared
等
