### ISSUE TITLE
这个是自身的崩溃吗（进入 fallback 模式后获取 backtrace 失败）

### ISSUE THREAD

**Issue by StephenNeverMore** [iqiyi/xCrash#16]
![image](https://user-images.githubusercontent.com/11781922/62589928-66a77d00-b8fd-11e9-9b3a-00c940b7d460.png)

 堆栈没有收集完整  就这些

**Comment by caikelun** [comment]
不是自身崩溃，是dumper模式失败了，走到了fallback模式，fallback模式下也没有拿到有用的信息。
能重现吗？xcrash版本号多少？请提供更多基本信息，谢谢。

**Comment by StephenNeverMore** [comment]
> 不是自身崩溃，是dumper模式失败了，走到了fallback模式，fallback模式下也没有拿到有用的信息。
> 能重现吗？xcrash版本号多少？请提供更多基本信息，谢谢。

没找到复现的规律， 我是fork的xcrash自己编译的lib 有推荐解决办法吗？

**Comment by caikelun** [comment]
目前没有。崩溃捕获其实是个成功率的，不能保证100%能捕获到。

**Comment by StephenNeverMore** [comment]
好的。多谢

发自我的 iPhone

**Comment by caikelun** [comment]
@StephenNeverMore 刚发了 2.3.0 版本，针对 fallback 模式做了很多优化，这种进入 fallback 模式后拿不到 backtrace 的情况应该能减少很多了。

**Comment by StephenNeverMore** [comment]
好的。多谢多谢


发自我的 iPhone

**Comment by StephenNeverMore** [comment]
@caikelun 更新2.3.0后，发现一个问题，和google的breakpad不能共存使用了，之前的版本是可以的，现在的版本会一直输出log：crashed APP's thread is running ...... 382且app不退出了。
另外一个问题，现在这个的方式获取java堆栈啊写文件操作啊  会不会造成卡顿？在应用崩溃退出之前。

**Comment by caikelun** [comment]
去掉breakpad或者仅运行xcrash_sample会有“app不退出”的问题吗？帮忙定位一下block在哪里？

写文件是会造成卡顿的，但是我觉得崩溃后优先还是要保证崩溃信息不能丢失。

**Comment by StephenNeverMore** [comment]
> 去掉breakpad或者仅运行xcrash_sample会有“app不退出”的问题吗？帮忙定位一下block在哪里？
> 
> 写文件是会造成卡顿的，但是我觉得崩溃后优先还是要保证崩溃信息不能丢失。

去掉breakpad没有问题的， 我要是会定位就不找你咯。 卡顿这个问题不好搞哈~
