### ISSUE TITLE
Native crash异常，能定位到代码哪个地方报错吗

### ISSUE THREAD

**Issue by yuanfangyan** [iqiyi/xCrash#18]
例如：signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0这样的问题

**Comment by caikelun** [comment]
可以根据backtrace，用addr2line解析出崩溃位置对应的代码行。可先参考下这个：https://source.android.com/devices/tech/debug/native-crash

**Comment by foobra** [comment]
> 可以根据backtrace，用addr2line解析出崩溃位置对应的代码行。可先参考下这个：https://source.android.com/devices/tech/debug/native-crash

能不能自动集成到xcrash里面, 自动显示出native行号?

**Comment by caikelun** [comment]
> > 可以根据backtrace，用addr2line解析出崩溃位置对应的代码行。可先参考下这个：https://source.android.com/devices/tech/debug/native-crash
> 
> 能不能自动集成到xcrash里面, 自动显示出native行号?

不可能这样做，线上运行的so没有符号，并且移动设备上也没有addr2line工具。

addr2line一般是在服务端做的，可以预先把so的“offset -> 符号 + 行号"信息保存到数据库中，在spark streaming或者flink之类的数据处理平台逻辑中完成addr2line的工作。
