### ISSUE TITLE
发现个bug，如果不给写存储卡的权限，java crash的callback不会走

### ISSUE THREAD

**Issue by ChineseBoyLY** [iqiyi/xCrash#2]
如果crash文件创建或者写失败(不给写存储卡的权限)， 此时java crash的callback也不会走，native crash的callback会走

**Comment by caikelun** [comment]
实践中，建议tombstone文件路径始终放在files目录中（默认是files/tombstones），这样不用考虑写入权限的问题。因为有些app的native崩溃是一启动就立刻发生了，来不及向用户要存储权限。

**Comment by caikelun** [comment]
@ChineseBoyLY 
刚才在新发的 2.1.2 版本中修复了这个问题，方便的话麻烦再验证一下。谢谢~
