### ISSUE TITLE
是否所有的native异常都能捕获?

### ISSUE THREAD

**Issue by foobra** [iqiyi/xCrash#20]
我发现有个空指针异常没有捕获 其他情况可以捕获.
ClassFoo *foo = nullptr;
foo->testFunc();

第二行crash的时候 无法捕获

**Comment by caikelun** [comment]
这种明显有问题的代码release编译时（-Os -Oz）一般都会被优化掉，比如编译成 exit 了。请反汇编确认。

此类测试代码建议用 -O0 编译。

**Comment by waruqi** [comment]
加个volatile 就好了。

```c
volatile ClassFoo *foo = nullptr;
foo->testFunc();
```

或者直接：`*((volatile int*)0) = 0;`

**Comment by foobra** [comment]
> 这种明显有问题的代码release编译时（-Os -Oz）一般都会被优化掉，比如编译成 exit 了。请反汇编确认。
> 
> 此类测试代码建议用 -O0 编译。

我只是举个例子, 这个ClassFoo很可能是外部传入的. 然后崩溃了. ndk自己都抓不到这种堆栈, xcrash是否能抓到?

**Comment by caikelun** [comment]
xCrash 的 log 文件能生成吗？还是说 log 文件中的 backtrace 为空？
另外可以确认下，是否在 xCrash 初始化之后，进程中又有其他地方注册了崩溃信号的 handler？
