### ISSUE TITLE
ANR在5.0前后采用不同的实现

### ISSUE THREAD

**Issue by oujunli** [iqiyi/xCrash#21]
ANR在5.0之间的版本通过Observe /data/anr变化来实现，为什么没有跟5.0之后一样，通过捕获信号量来实现？谢谢！

**Comment by caikelun** [comment]
4.x 上捕获 sigquit 信号是可以的，关键是捕获后怎么做；在 Dalvik 中没有 ART 这么明确好用的 public symbol 可以直接调用；而 4.x 设备目前的占有率已经很低，所以也不太值得再去研究类似 >= 5.0 上那种 dump 方案；另外，4.x 设备上 app 一般都是有权限访问 /data/anr 的，>= 5.0 设备上 app 基本都没有访问 /data/anr 的权限；所以在 4.x 和 >= 5.0 上使用了不用的 ANR 捕获方案。

**Comment by oujunli** [comment]
明白了，谢谢！
