### ISSUE TITLE
在自定义的信号处理函数中是否有必要兼容其他的信号处理函数呢

### ISSUE THREAD

**Issue by ljf1239848066** [iqiyi/xCrash#27]
我看Tencent Bugly里面会对其他信号处理进行兼容：
```
static void my_handler(const int code, siginfo_t *const si, void *const sc) {
...  
  /* Call previous handler. */  
  old_handler.sa_sigaction(code, si, sc);  
}
```
参考他们的文章:https://zhuanlan.zhihu.com/p/27834417
>某些信号可能在之前已经被安装过信号处理函数，而sigaction一个信号量只能注册一个处理函数，这意味着我们的处理函数会覆盖其他人的处理信号
>保存旧的处理函数，在处理完我们的信号处理函数后，在重新运行老的处理函数就能完成兼容。

所以在xcd_core_signal_handler里是否需要回调旧的信号处理函数呢？

**Comment by caikelun** [comment]
xCrash 默认会恢复上一个注册的 signal handler，处理方式和 bugly 是一样的，恢复的逻辑在这里：
https://github.com/iqiyi/xCrash/blob/master/src/native/libxcrash/jni/xc_crash.c#L407

如果不希望恢复之前的 signal handler，可以在初始化的时候设置 `setNativeRethrow(false)`。

**Comment by ljf1239848066** [comment]
好的，谢谢
