### ISSUE TITLE
XCrash.init() 必须在attachBaseContext里调用吗？ 必须是主线程调用吗？

### ISSUE THREAD

**Issue by yzhiw** [iqiyi/xCrash#30]
XCrash.init() 必须在attachBaseContext里调用吗？ 必须是主线程调用吗？
目前发现如果是后台线程调用init会抓取不到ANR信息。

**Comment by caikelun** [comment]
最好是在 `attachBaseContext` 中初始化，xCrash 初始化越早越好。（在 xCrash 初始化之前执行的 app 逻辑如果发生了崩溃，xCrash 是无法捕获到的）

目前 xCrash 使用的 `SIGQUIT` 拦截方案，只支持在主线程中调用。

**Comment by yzhiw** [comment]
好的，感谢答复。
