### ISSUE TITLE
一定需要ndk-R16b？可以用更高版本的NDK吗？或者低版本？

### ISSUE THREAD

**Issue by shenxiaolin** [iqiyi/xCrash#31]
编译环境mac, ndk/android-ndk-r10e

localhost:~ shx$ ndk-build --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

localhost:native shx$ ./build.sh
make: Entering directory `/Users/didi/Downloads/xCrash-master/src/native/libxcrash/jni'
[armeabi] Compile thumb  : xcrash <= xc_jni.c
arm-linux-androideabi-gcc: error: unrecognized command line option '-Weverything'
make: *** [/Users/didi/Downloads/xCrash-master/src/native/libxcrash/obj/local/armeabi/objs/xcrash/xc_jni.o] Error 1
make: Leaving directory `/Users/didi/Downloads/xCrash-master/src/native/libxcrash/jni'
make: Entering directory `/Users/didi/Downloads/xCrash-master/src/native/libxcrash_dumper/jni'
[armeabi] Compile thumb  : xcrash_dumper <= xcd_arm_exidx.c
arm-linux-androideabi-gcc: error: unrecognized command line option '-Weverything'
make: *** [/Users/didi/Downloads/xCrash-master/src/native/libxcrash_dumper/obj/local/armeabi/objs/xcrash_dumper//Users/didi/Downloads/xCrash-master/src/native/libxcrash_dumper/jni/xcd_arm_exidx.o] Error 1
make: Leaving directory `/Users/didi/Downloads/xCrash-master/src/native/libxcrash_dumper/jni'
localhost:native didi$ cat build.sh
#!/bin/bash

localhost:~shx$ whereis ndk-build
localhost:~ shx$ whereis ndk-build

**Comment by shenxiaolin** [comment]
将两个Android.mk 之中的-Weverything 移除；结果也是失败；

编译结果如下：
make: Entering directory `/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni'
[armeabi] Compile thumb  : xcrash <= xc_jni.c
[armeabi] Compile thumb  : xcrash <= xc_common.c
In file included from /Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/xc_common.c:37:0:
/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/xc_common.c: In function 'xc_common_open_log':
/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/../../common/xcc_util.h:65:35: error: 'SYS_getdents' undeclared (first use in this function)
 #define XCC_UTIL_SYSCALL_GETDENTS SYS_getdents
                                   ^
/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/xc_common.c:249:24: note: in expansion of macro 'XCC_UTIL_SYSCALL_GETDENTS'
     while((n = syscall(XCC_UTIL_SYSCALL_GETDENTS, fd, buf, sizeof(buf))) > 0)
                        ^
/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/../../common/xcc_util.h:65:35: note: each undeclared identifier is reported only once for each function it appears in
 #define XCC_UTIL_SYSCALL_GETDENTS SYS_getdents
                                   ^
/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/xc_common.c:249:24: note: in expansion of macro 'XCC_UTIL_SYSCALL_GETDENTS'
     while((n = syscall(XCC_UTIL_SYSCALL_GETDENTS, fd, buf, sizeof(buf))) > 0)
                        ^
/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni/xc_common.c:262:17: error: implicit declaration of function 'rename' [-Werror=implicit-function-declaration]
                 if(0 == rename(placeholder_pathname, pathname))
                 ^
cc1: all warnings being treated as errors
make: *** [/Users/shx/Downloads/xCrash-master/src/native/libxcrash/obj/local/armeabi/objs/xcrash/xc_common.o] Error 1
make: Leaving directory `/Users/shx/Downloads/xCrash-master/src/native/libxcrash/jni'
make: Entering directory `/Users/shx/Downloads/xCrash-master/src/native/libxcrash_dumper/jni'
[armeabi] Compile thumb  : xcrash_dumper <= xcd_arm_exidx.c
[armeabi] Compile thumb  : xcrash_dumper <= xcd_core.c
[armeabi] Compile thumb  : xcrash_dumper <= xcd_dwarf.c
/Users/shx/Downloads/xCrash-master/src/native/libxcrash_dumper/jni/xcd_dwarf.c: In function 'xcd_dwarf_read_encoded':
/Users/shx/Downloads/xCrash-master/src/native/libxcrash_dumper/jni/xcd_dwarf.c:585:9: error: implicit declaration of function '__builtin_add_overflow' [-Werror=implicit-function-declaration]
         if(__builtin_add_overflow(self->memory_cur_offset, sizeof(uintptr_t) - 1, &(self->memory_cur_offset))) return XCC_ERRNO_RANGE;
         ^
cc1: all warnings being treated as errors
make: *** [/Users/shx/Downloads/xCrash-master/src/native/libxcrash_dumper/obj/local/armeabi/objs/xcrash_dumper//Users/shx/Downloads/xCrash-master/src/native/libxcrash_dumper/jni/xcd_dwarf.o] Error 1
make: Leaving directory `/Users/shx/Downloads/xCrash-master/src/native/libxcrash_dumper/jni'

**Comment by caikelun** [comment]
是的，请用 r16b 吧，这是最后一个谷歌官方支持 armeabi 架构的 NDK 版本。目前来看，r16b 能满足需求。
