### ISSUE TITLE
无法及时捕获的traces信息

### ISSUE THREAD

**Issue by zhongxiaofeng** [iqiyi/xCrash#32]
接入之后，发现发生ANR时，不能及时捕获的traces信息，要等到第二次ANR时才能捕获到，有什么因素会干扰XCrash捕获ANR呢，在demo中接入时可以及时捕获到

**Comment by caikelun** [comment]
能复线的话，还是排除法分析下吧。因素很多：

* 进程中是否有其他sdk也注册了sigquit
* art有没有被hook

另外，目前xCrash捕捉ANR的方式（sigaction注册sigquit），对于主线程进入uninterruptible sleep（D）状态的block情况，是捕获不到的。

**Comment by zhongxiaofeng** [comment]
可能是有其他的SDK捕获ANR干扰。我疑惑的点是捕获ANR会延迟，并不是不能捕获，需要等到第二次ANR的时候才能捕获到

**Comment by caikelun** [comment]
因为android framework的ANR处理也是基于sigquit的，信号在进程中都是串行处理的。所以建议不要同时接入多个anr捕获方案，如果要线上灰度对比，建议使用类似设备ID尾号奇偶AB test的方式。（native crash捕获也是类似的情况）

在没有干扰的情况下，目前xCrash的捕获方案，应该是几乎没有延迟的，在系统判定process状态为not responding的时候，xCrash就会保存下anr dump文件的。

**Comment by zhongxiaofeng** [comment]
谢谢已经解决，发现是XCrash没有在主线程初始化导致的。

**Comment by zhongxiaofeng** [comment]
谢谢已经解决，发现是XCrash没有在主线程初始化导致的。
