### ISSUE TITLE
xcrash_sample   在5.0以上设备ANR没有回调

### ISSUE THREAD

**Issue by Sue-moonlight** [iqiyi/xCrash#33]
xcrash_sample 在**系统5.0以上**的设备    没有走ICrashCallback回调 麻烦帮忙看下
log下是显示
xcrash.sample Thread[3,tid=6022,WaitingInMainSignalCatcherLoop,Thread*=0x707d45ca00,peer=0x16702970,"Signal Catcher"]: reacting to signal 3
/xcrash.sample I/zygote64: Wrote stack traces to '/data/anr/traces.txt'

4.x是正常的

**Comment by caikelun** [comment]
请问问题现在还存在吗？

**Comment by Sue-moonlight** [comment]
你好&nbsp; &nbsp;还存在的&nbsp; &nbsp;
我用4.x是OK的&nbsp; &nbsp; &nbsp;5.0以上的时候&nbsp; &nbsp; 不走callback回调&nbsp; &nbsp; xcrash_sample里面的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"195936478"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月25日(星期二) 下午2:41
收件人:&nbsp;"iqiyi/xCrash"<xCrash@noreply.github.com&gt;;
抄送:&nbsp;"苏俊雄"<792392444@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [iqiyi/xCrash] xcrash_sample   在5.0以上设备ANR没有回调 (#33)




请问问题现在还存在吗？
