### ISSUE TITLE
请问Filemanager里面的placeholderCountMax有什么作用,代码没看懂

### ISSUE THREAD

**Issue by meijingkang** [iqiyi/xCrash#36]
请问Filemanager里面的placeholderCountMax有什么作用,代码没看懂

**Comment by caikelun** [comment]
表示当前需要保留的placeholder文件（后缀 ".clean.xcrash"）的最大数量。placeholder文件用于在磁盘上提前占位，应对崩溃/anr后由于磁盘空间满而无法写入tombstone信息的情况。

**Comment by meijingkang** [comment]
哦哦,懂了,谢谢谢谢
