### ISSUE TITLE
在多进程中的应用使用时，捕获不到子进程的 Anr。

### ISSUE THREAD

**Issue by heqiangflytosky** [iqiyi/xCrash#39]
主进程捕获anr是正常的，子进程捕获不到，不会调用callback。
如果需要提供其他信息，麻烦列举一下。

**Comment by caikelun** [comment]
目前不支持。原因是目前没找到合适的方法来判断service进程是否处于“no responding状态”。（主进程可以用getProcessesInErrorState检测，如源码中做的那样）
