### ISSUE TITLE
自己造成异常抓取好像在手机文件里面看不到错误日志啊，是不是操作有误呢？参照文档来的

### ISSUE THREAD

**Issue by WinWang** [iqiyi/xCrash#4]
自己造成异常抓取好像在手机文件里面看不到错误日志啊，是不是操作有误呢？参照文档来的

**Comment by caikelun** [comment]
你可以先直接运行 sample app 试一下。

**Comment by WinWang** [comment]
用demo试了下，在手机里面确实没有找到崩溃的debug.json文件

**Comment by caikelun** [comment]
按照你目前提供的信息量，我没法提供更多的帮助，抱歉。
请先自己调试和诊断一下？

**Comment by WinWang** [comment]
请问下如果生成的崩溃文件是在data/data文件夹下面才能看到吗？我看了下这个需要手机root才能查看的，没root的话我不就看不了了？

**Comment by caikelun** [comment]
运行sample app debug版，生成tombstone文件。adb直接查看：
```
$adb shell
$run-as xcrash.sample
$cd ./files/tombstones
$ls -al
```
你可以先了解一下：adb、linux user permission、android app debug/release version 等等的知识。

**Comment by WinWang** [comment]
好的，谢谢

**Comment by hejiafeng** [comment]
> 运行sample app debug版，生成tombstone文件。adb直接查看：
> 
> ```
> $adb shell
> $run-as xcrash.sample
> $cd ./files/tombstones
> $ls -al
> ```
> 
> 你可以先了解一下：adb、linux user permission、android app debug/release version 等等的知识。

release版本可以看嘛？我试了好像不行。

**Comment by caikelun** [comment]
release不能run-as，但是app自身的逻辑是可以读取内存存储的，release只要保证app自身逻辑能读取然后投递到服务端就可以了。
