### ISSUE TITLE
Task :xcrash_lib:checkstyle FAILED

### ISSUE THREAD

**Issue by Celinaxin** [iqiyi/xCrash#40]
我编译的时候，报这种错误

> Task :xcrash_lib:checkstyle FAILED
[ant:checkstyle] [ERROR] D:\Dev.space\xCrash-master_bak\xCrash-master\src\java\xcrash\xcrash_lib\src\main\java\xcrash\ActivityMonitor.java:1: 文件未以空行结尾▒? [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] D:\Dev.space\xCrash-master_bak\xCrash-master\src\java\xcrash\xcrash_lib\src\main\java\xcrash\AnrHandler.java:1: 文件未以空行结尾▒? [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] D:\Dev.space\xCrash-master_bak\xCrash-master\src\java\xcrash\xcrash_lib\src\main\java\xcrash\DefaultLogger.java:1: 文件未以空行结尾▒? [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] D:\Dev.space\xCrash-master_bak\xCrash-master\src\java\xcrash\xcrash_lib\src\main\java\xcrash\Errno.java:1: 文件未以空行结尾▒? [NewlineAtEndOfFile]

**Comment by caikelun** [comment]
自己修改或源码？或者\r\n的问题？建议和原始的文件二进制比对一下，我这边mac环境，:xcrash_lib:checkstyle是OK的。
