### ISSUE TITLE
建议将日志默认保存到SD卡Android/data目录

### ISSUE THREAD

**Issue by yihongyuelan** [iqiyi/xCrash#45]
非常感谢各位开源的xCrash方案，如果有想进一步了解原理的可以看看[这篇文章](http://www.itpub.net/2020/02/07/5193/)

虽然将日志保存到应用的内部存储目录(/data/data/pkg/files/tombstones)，可以避免申请权限，但如果此时设备无法使用网络，则无法将日志上传server端，release版本也没法直接获取日志。

建议将日志默认目录修改到Android/data/pkg/files/tombstones目录（getExternalFilesDir("tombstones").absolutePath），该目录同样可以避免申请SD卡读写权限，而且也能保证用户可以将日志从手机上拷贝出来。

诚然，在文档上有说明getExternalFilesDir有可能返回null，从当前来说几乎没有不带存储的设备了，为了避免这种极端的null，可以类似先判断，如果是null则存到App的私有data目录，反之则存到SD卡上。

val externalFolder = getExternalFilesDir("tombstones")
        if (externalFolder != null) {
            parameters.setLogDir(externalFolder.absolutePath)
        

 }

**Comment by caikelun** [comment]
默认放在内部存储，主要还是安全和隐私方面的考虑，不想引起不必要的麻烦，tombstone中包含一些内存的直接dump，还有logcat。

getExternalFilesDir获得的外部存储目录，shell用户是可以直接读取的（用户打开usb调试，连上pc/mac后，可能会被恶意程序直接读取）。。。如果开发时release版本调试需要，可以临时把存储目录设为外部存储。
