### ISSUE TITLE
是否可以添加上传指定服务器的功能

### ISSUE THREAD

**Issue by xuyabin521** [iqiyi/xCrash#47]
发布后是不方便查看用户设备的，是否可以把crash log上传到指定服务器？

**Comment by xuqnqn** [comment]
xCrash里面实现了TombstoneParser，可以把tombstone文件解析成json obj，方便http上传。大家可以自己再封装一下把崩溃日志上传服务器

**Comment by caikelun** [comment]
app一般都各自有自己的网络库，“投递”这种功能放在xCrash的通用SDK里不合适，也没有必要。
