### ISSUE TITLE
Ubuntu环境下编译native出错

### ISSUE THREAD

**Issue by zzulevi** [iqiyi/xCrash#48]
系统环境：
Linux version 4.15.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
NDK版本：21.0.6113669
编译时提示：
src/native/libxcrash/jni/xc_crash.c:464:13: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
src/native/libxcrash_dumper/jni/lzma/Bra.c:37:24: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
src/native/libxcrash_dumper/jni/lzma/Bra.c:58:24: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
![2020-09-21_113435](https://user-images.githubusercontent.com/30970716/93731449-9b5cbd80-fbff-11ea-8f09-04face494194.png)

**Comment by xuqnqn** [comment]
Ubuntu 7.3.0 ？ Ubuntu是什么版本的？ndk 是什么版本的？

**Comment by xuqnqn** [comment]
已经适配android-ndk-r21b编译, commit 到dev branch 了
