### ISSUE TITLE
为什么不用cmake呢？

### ISSUE THREAD

**Issue by wangli135** [iqiyi/xCrash#5]
为什么不用cmake呢？是因为dumper是个可执行程序的原因吗？如果放在AndroidStudio里是不是编译就有问题，如果单独用命令执行，也需要有个重命名的过程？

**Comment by caikelun** [comment]
没用cmake仅仅是个人习惯问题。
用cmake的话，应该也可以写一些附加的运行脚本来完成重命名工作吧，这个我不太清楚。

**Comment by wangli135** [comment]
是的，要么附加的脚本；要么gradle插件，应该可以的，后者还没实践过

**Comment by caikelun** [comment]
@wangli135 可以参考一下这个 PR 的实现：https://github.com/iqiyi/xCrash/pull/11
