### ISSUE TITLE
native crash happened on android 10

### ISSUE THREAD

**Issue by t12x3456** [iqiyi/xCrash#53]
dump status:
child terminated normally with non-zero exit status(102)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Start time: '2020-10-28T00:52:16.530-0300'
Crash time: '2020-10-28T02:47:40.345-0300'
App ID: 'com.***.***'
App version: '7.5.74'
Rooted: 'No'
API level: '29'
OS version: '10'
Kernel version: 'Linux version 4.9.206-perf+ #1 SMP PREEMPT Wed Sep 30 23:50:55 CDT 2020 (aarch64)'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'motorola'
Brand: 'motorola'
Model: 'moto g(7) power'
Build fingerprint: 'motorola/ocean_t/ocean_t:10/QPOS30.52-29-9/0c526b:user/release-keys'
ABI: 'arm64'
pid: 32393, tid: 32418, name: xcrash_trace_dp  >>> com.***.*** <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0  0000000000000000  x1  0000000000007ea2  x2  0000000000000006  x3  00000070c0e62080
    x4  00000070a53147c0  x5  00000070a53147c0  x6  00000070a53147c0  x7  00000070c1ea9240
    x8  00000000000000f0  x9  900c3b2804db1c32  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 000000711b97d740  x14 0000000000000001  x15 404511a01c84f6c1
    x16 00000071af4f38c0  x17 00000071af4d1020  x18 00000070c0172000  x19 0000000000007e89
    x20 0000000000007ea2  x21 00000000ffffffff  x22 00000070a8e5b4c0  x23 000000712c5d5835
    x24 000000712c5f749e  x25 0000000000000001  x26 000000712cbf7258  x27 00000071b225c880
    x28 0000000000000000  x29 00000070c0e62120
    sp  00000070c0e62060  lr  00000071af485f88  pc  00000071af485fb4

backtrace:
    #00 pc 0000000000082fb4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
    #01 pc 00000000004b4850  /apex/com.android.runtime/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+2272)
    #02 pc 000000000000c5b8  /system/lib64/libbase.so (_ZN7android4base10LogMessageD1Ev+612)
    #03 pc 0000000000442f54  /apex/com.android.runtime/lib64/libart.so (_ZNK3art9OatHeader17GetCompilerFilterEv+284)
    #04 pc 000000000044a84c  /apex/com.android.runtime/lib64/libart.so (_ZNK3art7OatFile17GetCompilerFilterEv+44)
    #05 pc 0000000000455d00  /apex/com.android.runtime/lib64/libart.so (_ZN3art14OatFileManager14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+380)
    #06 pc 00000000004c1d40  /apex/com.android.runtime/lib64/libart.so (_ZN3art7Runtime14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+108)
    #07 pc 000000000000648c  /data/app/com.***.***-HCMqtsa_bMSx6IjK9XhC8A==/lib/arm64/libxcrash.so
    #08 pc 00000000000e2060  /apex/com.android.runtime/lib64/bionic/libc.so
    #09 pc 0000000000084af4  /apex/com.android.runtime/lib64/bionic/libc.so
    #10 pc 0000000000000000  

java stacktrace:
  (no managed stack frames)

memory info:
 System Summary (From: /proc/meminfo)
  MemTotal:        3659320 kB
  MemFree:           26988 kB
  MemAvailable:     372516 kB
  Buffers:             364 kB
  Cached:           432912 kB
  SwapCached:        11820 kB
  Active:          1423040 kB
  Inactive:         580504 kB
  Active(anon):    1261180 kB
  Inactive(anon):   417984 kB
  Active(file):     161860 kB
  Inactive(file):   162520 kB
  Unevictable:       56648 kB
  Mlocked:           56648 kB
  SwapTotal:       1048572 kB
  SwapFree:          12320 kB
  Dirty:               820 kB
  Writeback:            36 kB
  AnonPages:       1623164 kB
  Mapped:           360252 kB
  Shmem:             51428 kB
  Slab:             342536 kB
  SReclaimable:      88548 kB
  SUnreclaim:       253988 kB
  KernelStack:       67440 kB
  PageTables:        86708 kB
  NFS_Unstable:          0 kB
  Bounce:                0 kB
  WritebackTmp:          0 kB
  CommitLimit:     2878232 kB
  Committed_AS:   58449580 kB
  VmallocTotal:   263061440 kB
  VmallocUsed:           0 kB
  VmallocChunk:          0 kB
  CmaTotal:         258048 kB
  CmaFree:               0 kB
-
 Process Status (From: /proc/PID/status)
  Name:	com.***.***
  Umask:	0077
  State:	D (disk sleep)
  Tgid:	32393
  Ngid:	0
  Pid:	32393
  PPid:	984
  TracerPid:	0
  Uid:	10273	10273	10273	10273
  Gid:	10273	10273	10273	10273
  FDSize:	512
  Groups:	3001 3002 3003 9997 20273 50273
  VmPeak:	10103188 kB
  VmSize:	 9672364 kB
  VmLck:	       0 kB
  VmPin:	       0 kB
  VmHWM:	  384028 kB
  VmRSS:	  179528 kB
  RssAnon:	  127732 kB
  RssFile:	   42300 kB
  RssShmem:	    9496 kB
  VmData:	 1570940 kB
  VmStk:	    8192 kB
  VmExe:	      28 kB
  VmLib:	  221692 kB
  VmPTE:	    3360 kB
  VmPMD:	      52 kB
  VmSwap:	   47632 kB
  Threads:	252
  SigQ:	3/13161
  SigPnd:	0000000000000000
  ShdPnd:	0000000000000000
  SigBlk:	0000000080001200
  SigIgn:	0000000000000001
  SigCgt:	0000000e400084fc
  CapInh:	0000000000000000
  CapPrm:	0000000000000000
  CapEff:	0000000000000000
  CapBnd:	0000000000000000
  CapAmb:	0000000000000000
  Seccomp:	2
  Speculation_Store_Bypass:	unknown
  Cpus_allowed:	ff
  Cpus_allowed_list:	0-7
  Mems_allowed:	1
  Mems_allowed_list:	0
  voluntary_ctxt_switches:	575033
  nonvoluntary_ctxt_switches:	808913
-
 Process Limits (From: /proc/PID/limits)
  Limit                     Soft Limit           Hard Limit           Units
  Max cpu time              unlimited            unlimited            seconds
  Max file size             unlimited            unlimited            bytes
  Max data size             unlimited            unlimited            bytes
  Max stack size            8388608              unlimited            bytes
  Max core file size        0                    unlimited            bytes
  Max resident set          unlimited            unlimited            bytes
  Max processes             13161                13161                processes
  Max open files            32768                32768                files
  Max locked memory         67108864             67108864             bytes
  Max address space         unlimited            unlimited            bytes
  Max file locks            unlimited            unlimited            locks
  Max pending signals       13161                13161                signals
  Max msgqueue size         819200               819200               bytes
  Max nice priority         40                   40
  Max realtime priority     0                    0
  Max realtime timeout      unlimited            unlimited            us
-
 Process Details (From: /proc/PID/smaps)
                   Pss      Pss   Shared  Private   Shared  Private  SwapPss
                 Total    Clean    Dirty    Dirty    Clean    Clean    Dirty
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    74234        0      500    74224        0        0    29594
  Dalvik Heap        0        0        0        0        0        0        0
        Stack       60        0        4       60        0        0       24
       Cursor      416        0        0      416        0        0        0
       Ashmem        4        0        0        4       20        0        0
      Gfx dev     7272        0        0     7272        0        0        0
    Other dev       32        0      180        0        0       32        0
     .so mmap     7004     3820     1888     1400    14400     3820      519
    .jar mmap      868      324        0        0     6748      324        0
    .apk mmap      529      332        0       60      628      332      140
    .dex mmap     9317     9272        0       28       60     9272        0
    .oat mmap      772       96        0       64    14780       96        0
    .art mmap     3690        0     9436     3480       40        0       85
   Other mmap     5896        0     6876     2028      380      388        0
      Unknown    60773        0      788    60756        0        0    10133
        TOTAL   211362    13844    19672   149792    37056    14264    40495
-
 Process Dalvik Details (From: /proc/PID/smaps)
   .Boot vdex       54       52        0        0       12       52        0
     .App dex       77       36        0       28       40       36        0
    .App vdex     9186     9184        0        0        8     9184        0
    .Boot art     3690        0     9436     3480       40        0       85
-
 Process Summary (From: /proc/PID/smaps)
                       Pss(KB)
                        ------
           Java Heap:     3480
         Native Heap:    74224
                Code:    15396
               Stack:       60
       Private Other:    70896
              System:    47306
               TOTAL:   211362       TOTAL SWAP PSS:    40495
-

memory info:
 Process Summary (From: android.os.Debug.MemoryInfo)
                       Pss(KB)
                        ------
           Java Heap:    50440
         Native Heap:    77584
                Code:    16648
               Stack:       60
            Graphics:    10752
       Private Other:    17600
              System:    47317
               TOTAL:   220401           TOTAL SWAP:    46972

foreground:
no

**Comment by xuqnqn** [comment]
_ZN3art7Runtime14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE
this is ANR happened, xcrash call ART's DumpForSigQuit to dump trace, ART aborted itself, xcrash doesn't do anything special
what version are you using?

**Comment by xuqnqn** [comment]
pls use latest 3.0.0

**Comment by t12x3456** [comment]
Got it, i wiill try

**Comment by t12x3456** [comment]
Got it, i will try this version
