### ISSUE TITLE
开启ANR检测功能是不是也会捕获普通卡顿

### ISSUE THREAD

**Issue by DaneChen** [iqiyi/xCrash#54]
非常感谢贵厂的库。
使用中遇到个问题：开启ANR功能后，普通的卡顿也会上传, 主线程被短暂卡顿也会上传一个anr日志，导致线上传回的日志非常多。
有没有接口可以调整这个卡顿检测的时间阈值 ？

**Comment by xuqnqn** [comment]
你是在什么OS版本上发现会上传卡顿日志？正常情况下xcrash 开启ANR功能后，不会捕获卡顿的，你仔细检查一下你那确定是短暂卡顿吗？
