### ISSUE TITLE
每个log文件都是512KB,如何优化?

### ISSUE THREAD

**Issue by ccj659** [iqiyi/xCrash#55]
![image](https://user-images.githubusercontent.com/15311346/98194002-601d1080-1f59-11eb-815a-d3eb719a23f5.png)

**Comment by caikelun** [comment]
逻辑上是可以优化的。你应该是开启了placeholder机制，如果节省flash占用的需求比较优化，建议关闭placeholder机制。

开启placeholder机制后，在写入崩溃信息后，目前没有做shrink的原因是“考虑到tombstone文件的回收复用”，就是tombstone信息被投递后，可以再次回收成placeholder文件。而且一般不会保留太多的tombstone文件（默认10个），所以就没有考虑这么多。

也许在初始化时，可以增加一个选项，控制“在placeholder文件中写完崩溃信息后，是否要做shrink”。

**Comment by ccj659** [comment]
好的,感谢老哥.
