### ISSUE TITLE
部分native堆栈信息不全 只有地址    #00 pc 701a05a8  没有对应so包

### ISSUE THREAD

**Issue by lanlianhuashi** [iqiyi/xCrash#60]
dump status:
child terminated normally with non-zero exit status(102)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Start time: '2020-11-27T09:39:48.728-0300'
Crash time: '2020-11-27T09:43:52.566-0300'
App ID: 'com.xx'
App version: '6.0.0'
Rooted: 'No'
API level: '27'
OS version: '8.1.0'
Kernel version: 'Linux version 3.18.71-perf-g8a728bd #1 SMP PREEMPT Tue Oct 9 13:57:37 CDT 2018 (armv7l)'
ABI list: 'armeabi-v7a,armeabi'
Manufacturer: 'motorola'
Brand: 'motorola'
Model: 'Moto G (5S) Plus'
Build fingerprint: 'motorola/sanders_nt/sanders_nt:8.1.0/OPSS28.65-36-3/4af3:user/release-keys'
ABI: 'arm'
pid: 8091, tid: 8150, name: logger-logback-  >>> com.xx <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x701a05a8
    r0  6fc8d014  r1  6fd8b440  r2  15a7eba8  r3  00000000
    r4  0000007f  r5  6fd8b440  r6  00000000  r7  15a7eba8
    r8  00000000  r9  908e3600  r10 6fd794c0  r11 6fbc1e70
    ip  6fb8cf88  sp  8fdd5030  lr  706a944f  pc  701a05a8

backtrace:
    #00 pc 701a05a8  

java stacktrace:
  at java.lang.ref.Reference.getReferent(Native method)
  at java.lang.ref.Reference.get(Reference.java:98)
  at java.security.Provider$Service.getImplClass(Provider.java:1669)
  at java.security.Provider$Service.newInstance(Provider.java:1631)
  at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2643)
  at javax.crypto.Cipher.tryCombinations(Cipher.java:2575)
  at javax.crypto.Cipher.createCipher(Cipher.java:522)
  at javax.crypto.Cipher.getInstance(Cipher.java:414)
  at com.xx.sdk.logging.i$a.a(LogbackExecutor.java:296)
  at com.xx.sdk.logging.i.b(LogbackExecutor.java:222)
  at com.xx.sdk.logging.i.a(LogbackExecutor.java:163)
  at com.xx.sdk.logging.i.a(LogbackExecutor.java:27)
  at com.xx.sdk.logging.i$c.run(LogbackExecutor.java:141)

memory info:
 System Summary (From: /proc/meminfo)
  MemTotal:        2925748 kB
  MemFree:          107864 kB
  MemAvailable:    1395220 kB
  Buffers:           13568 kB
  Cached:          1325856 kB
  SwapCached:         2252 kB
  Active:          1313924 kB
  Inactive:         882900 kB
  Active(anon):     689348 kB
  Inactive(anon):   175152 kB
  Active(file):     624576 kB
  Inactive(file):   707748 kB
  Unevictable:         260 kB
  Mlocked:             260 kB
  HighTotal:       2300300 kB
  HighFree:          27772 kB
  LowTotal:         625448 kB
  LowFree:           80092 kB
  SwapTotal:        524284 kB
  SwapFree:         465804 kB
  Dirty:              1548 kB
  Writeback:             0 kB
  AnonPages:        857732 kB
  Mapped:           715588 kB
  Shmem:              7124 kB
  Slab:             101948 kB
  SReclaimable:      35804 kB
  SUnreclaim:        66144 kB
  KernelStack:       20080 kB
  PageTables:        41040 kB
  NFS_Unstable:          0 kB
  Bounce:                0 kB
  WritebackTmp:          0 kB
  CommitLimit:     1987156 kB
  Committed_AS:   55814496 kB
  VmallocTotal:     358400 kB
  VmallocUsed:      198620 kB
  VmallocChunk:      31044 kB
-
 Process Status (From: /proc/PID/status)
  Name:	com.taxis99
  State:	S (sleeping)
  Tgid:	8091
  Pid:	8091
  PPid:	1126
  TracerPid:	0
  Uid:	10160	10160	10160	10160
  Gid:	10160	10160	10160	10160
  Ngid:	0
  FDSize:	512
  Groups:	3001 3002 3003 9997 20160 50160
  VmPeak:	 2110760 kB
  VmSize:	 2097112 kB
  VmLck:	       0 kB
  VmPin:	       0 kB
  VmHWM:	  456084 kB
  VmRSS:	  455240 kB
  VmData:	  458304 kB
  VmStk:	    8192 kB
  VmExe:	      20 kB
  VmLib:	  168592 kB
  VmPTE:	    1146 kB
  VmSwap:	       0 kB
  Threads:	210
  SigQ:	0/21051
  SigPnd:	0000000000000000
  ShdPnd:	0000000000000000
  SigBlk:	0000000000001204
  SigIgn:	0000000000001000
  SigCgt:	00000006400084f8
  CapInh:	0000000000000000
  CapPrm:	0000000000000000
  CapEff:	0000000000000000
  CapBnd:	0000000000000000
  CapAmb:	0000000000000000
  Seccomp:	2
  Cpus_allowed:	ff
  Cpus_allowed_list:	0-7
  voluntary_ctxt_switches:	28108
  nonvoluntary_ctxt_switches:	18479
-
 Process Limits (From: /proc/PID/limits)
  Limit                     Soft Limit           Hard Limit           Units
  Max cpu time              unlimited            unlimited            seconds
  Max file size             unlimited            unlimited            bytes
  Max data size             unlimited            unlimited            bytes
  Max stack size            8388608              unlimited            bytes
  Max core file size        0                    unlimited            bytes
  Max resident set          unlimited            unlimited            bytes
  Max processes             21051                21051                processes
  Max open files            4096                 4096                 files
  Max locked memory         67108864             67108864             bytes
  Max address space         unlimited            unlimited            bytes
  Max file locks            unlimited            unlimited            locks
  Max pending signals       21051                21051                signals
  Max msgqueue size         819200               819200               bytes
  Max nice priority         40                   40
  Max realtime priority     0                    0
  Max realtime timeout      unlimited            unlimited            us
-
 Process Details (From: /proc/PID/smaps)
                   Pss      Pss   Shared  Private   Shared  Private  SwapPss
                 Total    Clean    Dirty    Dirty    Clean    Clean    Dirty
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    89502        0     1048    89468        0        0        0
  Dalvik Heap    46472        0     1160    46456        0        0        0
 Dalvik Other    13129        0       64    13128        0        0        0
        Stack     3160        0        0     3160        0        0        0
       Ashmem     2258        0      468     2024       16        0        0
      Gfx dev   138696        0        0   138696        0        0        0
    Other dev       28        0      116        0        0       28        0
     .so mmap    14891    12264     2320      736    19764    12264        0
    .jar mmap        0        0        0        0        4        0        0
    .apk mmap     4761     2024        0       52    18748     2024        0
    .ttf mmap       87        0        0        0      404        0        0
    .dex mmap    47510    44084        0       20    18364    44084        0
    .oat mmap     1756      240       80        0    15224      240        0
    .art mmap     1046       12      596      860     6528       12        0
   Other mmap      370        0       12        4     1568      104        0
      Unknown     7433        0      204     7432        0        0        0
        TOTAL   371099    58624     6068   302036    80620    58756        0
-
 Process Dalvik Details (From: /proc/PID/smaps)
        .Heap    41580        0        0    41580        0        0        0
         .LOS     4530        0      860     4520        0        0        0
      .Zygote      206        0      300      200        0        0        0
   .NonMoving      156        0        0      156        0        0        0
 .LinearAlloc     8837        0       52     8836        0        0        0
          .GC      176        0        8      176        0        0        0
    .JITCache     3448        0        0     3448        0        0        0
 .IndirectRef      668        0        4      668        0        0        0
   .Boot vdex     1333      364        0        0    12168      364        0
     .App dex      929      608        0       20      732      608        0
    .App vdex    45248    43112        0        0     5464    43112        0
    .Boot art     1046       12      596      860     6528       12        0
-
 Process Summary (From: /proc/PID/smaps)
                       Pss(KB)
                        ------
           Java Heap:    47328
         Native Heap:    89468
                Code:    59420
               Stack:     3160
       Private Other:   161416
              System:    10307
               TOTAL:   371099       TOTAL SWAP PSS:        0
-

memory info:
 Process Summary (From: android.os.Debug.MemoryInfo)
                       Pss(KB)
                        ------
           Java Heap:    53332
         Native Heap:   101216
                Code:    59420
               Stack:     3216
            Graphics:   138508
       Private Other:    22964
              System:    10308
               TOTAL:   388964           TOTAL SWAP:        0

foreground:
yes
==================还有这种情况 前边都正常，但最后一行只有地址，没有对应so包的名称==================
dump status:
child terminated normally with non-zero exit status(102)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Start time: '2020-11-28T00:55:39.510-0300'
Crash time: '2020-11-28T01:49:02.572-0300'
App ID: 'com.xx'
App version: '6.0.1'
Rooted: 'No'
API level: '22'
OS version: '5.1.1'
Kernel version: 'Linux version 3.10.65-1235336 #2 SMP PREEMPT Tue Sep 12 21:51:38 KST 2017 (armv7l)'
ABI list: 'armeabi-v7a,armeabi'
Manufacturer: 'samsung'
Brand: 'samsung'
Model: 'SM-G531H'
Build fingerprint: 'samsung/grandprimeve3gub/grandprimeve3g:5.1.1/LMY48B/G531HVJU0AQI1:user/release-keys'
ABI: 'arm'
pid: 19069, tid: 19069, name: com.xx  >>> com.xx <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x81010964
    r0  fffffb2c  r1  beda17e8  r2  b47ff010  r3  70d51f00
    r4  b48e4300  r5  b25f6000  r6  81010958  r7  23c69000
    r8  b488a070  r9  00000001  r10 b488a070  r11 beda17e8
    ip  beda17e8  sp  beda1790  lr  b46398a9  pc  b46385a2

backtrace:
    #00 pc 0012c5a2  libart.so
    #01 pc 0012d8a5  libart.so (_ZN3art2gc9collector9SemiSpace16ProcessMarkStackEv+112)
    #02 pc 0012da15  libart.so (_ZN3art2gc9collector9SemiSpace20MarkReachableObjectsEv+308)
    #03 pc 0012de45  libart.so (_ZN3art2gc9collector9SemiSpace12MarkingPhaseEv+372)
    #04 pc 0012b821  libart.so (_ZN3art2gc9collector9SemiSpace9RunPhasesEv+168)
    #05 pc 0011ff01  libart.so (_ZN3art2gc9collector16GarbageCollector3RunENS0_7GcCauseEb+232)
    #06 pc 0013d537  libart.so (_ZN3art2gc4Heap22CollectGarbageInternalENS0_9collector6GcTypeENS0_7GcCauseEb+1382)
    #07 pc 0013ec81  libart.so (_ZN3art2gc4Heap22AllocateInternalWithGcEPNS_6ThreadENS0_13AllocatorTypeEjPjS5_PPNS_6mirror5ClassE+232)
    #08 pc 0027a3d9  libart.so
    #09 pc 0027ae4d  libart.so (artAllocArrayFromCodeBumpPointer+124)
    #10 pc 000a274f  libart.so
    #11 pc 7362331f  

java stacktrace:
  at java.lang.AbstractStringBuilder.(AbstractStringBuilder.java:76)
  at java.lang.StringBuilder.(StringBuilder.java:54)
  at java.lang.Object.toString(Object.java:354)
  at java.lang.StringBuilder.append(StringBuilder.java:202)
  at android.os.Looper.loop(Looper.java:138)
  at android.app.ActivityThread.main(ActivityThread.java:5910)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

memory info:
 System Summary (From: /proc/meminfo)
  MemTotal:         979676 kB
  MemFree:           32740 kB
  Buffers:            5880 kB
  Cached:           307576 kB
  SwapCached:        35700 kB
  Active:           344560 kB
  Inactive:         344208 kB
  Active(anon):     185840 kB
  Inactive(anon):   193000 kB
  Active(file):     158720 kB
  Inactive(file):   151208 kB
  Unevictable:        3268 kB
  Mlocked:               0 kB
  HighTotal:        270336 kB
  HighFree:           3008 kB
  LowTotal:         709340 kB
  LowFree:           29732 kB
  SwapTotal:        524284 kB
  SwapFree:         300336 kB
  Dirty:                12 kB
  Writeback:             0 kB
  AnonPages:        370716 kB
  Mapped:           142368 kB
  Shmem:               228 kB
  Slab:              48212 kB
  SReclaimable:      19412 kB
  SUnreclaim:        28800 kB
  KernelStack:        8744 kB
  PageTables:        14348 kB
  NFS_Unstable:          0 kB
  Bounce:                0 kB
  WritebackTmp:          0 kB
  CommitLimit:     1014120 kB
  Committed_AS:   14441328 kB
  VmallocTotal:     245760 kB
  VmallocUsed:      125228 kB
  VmallocChunk:      33652 kB
-
 Process Status (From: /proc/PID/status)
  Name: com.taxis99
  State:  R (running)
  Tgid: 19069
  Pid:  19069
  PPid: 21737
  TracerPid:  0
  Uid:  10149 10149 10149 10149
  Gid:  10149 10149 10149 10149
  FDSize: 512
  Groups: 1015 1028 3001 3002 3003 9997 50149
  VmPeak:  1516272 kB
  VmSize:  1412132 kB
  VmLck:         0 kB
  VmPin:         0 kB
  VmHWM:    218392 kB
  VmRSS:    111140 kB
  VmData:   279980 kB
  VmStk:      8192 kB
  VmExe:        12 kB
  VmLib:    191136 kB
  VmPTE:       850 kB
  VmSwap:    35376 kB
  Threads:  149
  SigQ: 5/7637
  SigPnd: 0000000000000000
  ShdPnd: 0000000000000000
  SigBlk: 0000000000001604
  SigIgn: 0000000000001000
  SigCgt: 00000002000084fc
  CapInh: 0000000000000000
  CapPrm: 0000000000000000
  CapEff: 0000000000000000
  CapBnd: 0000000000000000
  Seccomp:  0
  Cpus_allowed: f
  Cpus_allowed_list:  0-3
  voluntary_ctxt_switches:  216601
  nonvoluntary_ctxt_switches: 359854
-
 Process Limits (From: /proc/PID/limits)
  Limit                     Soft Limit           Hard Limit           Units
  Max cpu time              unlimited            unlimited            seconds
  Max file size             unlimited            unlimited            bytes
  Max data size             unlimited            unlimited            bytes
  Max stack size            8388608              unlimited            bytes
  Max core file size        2147483647           2147483647           bytes
  Max resident set          unlimited            unlimited            bytes
  Max processes             7637                 7637                 processes
  Max open files            4096                 4096                 files
  Max locked memory         67108864             67108864             bytes
  Max address space         unlimited            unlimited            bytes
  Max file locks            unlimited            unlimited            locks
  Max pending signals       7637                 7637                 signals
  Max msgqueue size         819200               819200               bytes
  Max nice priority         40                   40
  Max realtime priority     0                    0
  Max realtime timeout      unlimited            unlimited            us
-
 Process Details (From: /proc/PID/smaps)
                   Pss      Pss   Shared  Private   Shared  Private     Swap
                 Total    Clean    Dirty    Dirty    Clean    Clean    Dirty
                ------   ------   ------   ------   ------   ------   ------
  Native Heap     6133        0     1648     5408      148      628    12020
  Dalvik Heap    57344        0      928    56876     2644       76    12780
 Dalvik Other      735        0       32      732       12        0       60
        Stack     1636        0       24     1436        0      200     2908
    Other dev       21        0       60        0        0       20        0
     .so mmap     6474     3220      408      152    11464     3220     1424
    .apk mmap     1047      912        0        0      696      912        0
    .ttf mmap       16        4        0        0       52        4        0
    .dex mmap     3516     3316        0        0      400     3316        0
    .oat mmap     2355      132        0        0    14808      132        0
    .art mmap     1943       84     1368     1084     6304       84      188
   Other mmap       74        0        4        4      348       16        0
      Unknown      403        0       16      328       20       68     5720
        TOTAL    81697     7668     4488    66020    36896     8676    35100
-
 Process Dalvik Details (From: /proc/PID/smaps)
        .Heap    44156        0        0    44156        0        0        0
         .LOS      430        0      208      320        0       60    10236
      .Zygote      542        0      720      188     2644       12     2504
   .NonMoving    12216        0        0    12212        0        4       40
          .GC      615        0       24      612       12        0       60
 .IndirectRef      120        0        8      120        0        0        0
     .App dex     3516     3316        0        0      400     3316        0
    .Boot art     1943       84     1368     1084     6304       84      188
-
 Process Summary (From: /proc/PID/smaps)
                       Pss(KB)
                        ------
           Java Heap:    58044
         Native Heap:     5408
                Code:     7736
               Stack:     1436
       Private Other:     1168
              System:     7001
               TOTAL:    81697           TOTAL SWAP:    35100
-

**Comment by xuqnqn** [comment]
你用的是什么版本的ndk？老版本的NDK unwind 逻辑有问题，会导致栈回溯失败。试试最新版本的ndk？

**Comment by xuqnqn** [comment]
#00 pc 701a05a8 没有对应so包。结合maps文件看一下是否有0x701a0000这块区域，如果没有的话，说明程序跑飞了

**Comment by lanlianhuashi** [comment]
好的，我看看，多谢
