### ISSUE TITLE
ANR信息捕捉问题

### ISSUE THREAD

**Issue by TomLettuces** [iqiyi/xCrash#61]
使用xcrash_sample测试ANR的时候，发现没有生成tombstone_开头的文件，java crash和native crash都可以正常生成。
通过adb bugreport命令生成文件查看发现是有anr文件的。手机型号三星S9，Android 10。

**Comment by TomLettuces** [comment]
目前进展是发现Util的checkProcessAnrState方法中获取am.getProcessesInErrorState()为空，就直接return了。但是系统的没有响应弹框已经弹出了。anrCheckProcessState需要设置为false。

**Comment by ccj659** [comment]
我也发现了相同问题, ANR信息无法捕获,但是bugly和友盟可以捕获.

**Comment by ccj659** [comment]
` fileObserver = new FileObserver("/data/anr/", CLOSE_WRITE) {
            public void onEvent(int event, String path) { //ANR发生是,没有进入该逻辑
                try {
                    if (path != null) {
                        String filepath = "/data/anr/" + path;`

**Comment by ccj659** [comment]
这个ANR的问题, 我打算用ANRWatchDog的思路方式来实现了..

**Comment by TomLettuces** [comment]
@ccj659 初始化参数setAnrCheckProcessState设置为false试试

**Comment by t12x3456** [comment]
> ```
>  fileObserver = new FileObserver("/data/anr/", CLOSE_WRITE) {
>             public void onEvent(int event, String path) { //ANR发生时,没有进入该逻辑
>                 try {
>                     if (path != null) {
>                         String filepath = "/data/anr/" + path;
> ```
> 
> ![image](https://user-images.githubusercontent.com/15311346/102311009-0e7b9300-3fa7-11eb-8a30-016b75fa8eea.png)
FileObserver只能5.0以下，5.0以上没这个目录权限了，走的signal catch的逻辑

**Comment by xuqnqn** [comment]
是的，在部分机型上，am.getProcessesInErrorState()为空，导致在用getProcessesInErrorState来确认ANR状态时，将xcrash捕获 ANR 的中间文件trace.xcrash删掉了。可以在xcrash.init时，用setAnrCheckProcessState设置false，来解决这个问题。
