### ISSUE TITLE
初始化init() 时 couldn't find "libxcrash.so", NativeHandler System.loadLibrary failed

### ISSUE THREAD

**Issue by funwaywang** [iqiyi/xCrash#68]
非常感谢您的帮助. 我按照README文档指引,  在Application 里面调用 XCrash.init(this) 时, logcat显示异常 

> 2021-01-18 09:38:32.701 4715-4715/com.example.xxxx E/xcrash: NativeHandler System.loadLibrary failed
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.xxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.xxxx-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libxcrash.so"        
at java.lang.Runtime.loadLibrary0(Runtime.java:984)
at java.lang.System.loadLibrary(System.java:1530)
at xcrash.NativeHandler.initialize(NativeHandler.java:85)
at xcrash.XCrash.init(XCrash.java:188)

gradle里面配置:

> .....
ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
......
implementation 'com.iqiyi.xcrash:xcrash-android-lib:3.0.0'

开发工具是 Android Studio 4.1.2, xCrash 版本 3.0.0, 测试手机android版本7.1
我尝试过用自己编译的库, 问题还是依旧. 请问我哪里做错了? 非常感谢

**Comment by funwaywang** [comment]
问题找到了, 原来在build.gradle 里面加了 packagingOptions{exclude '**.**'}

**Comment by superoidlau** [comment]
> 问题找到了, 原来在build.gradle 里面加了 packagingOptions{exclude '**.**'}

I do not have this configuration item in build.gradle, and still get this error.
device:  Mi Note 3   OS version：6.0.1
