### ISSUE TITLE
xCrash和umeng性能监控不能一起使用

### ISSUE THREAD

**Issue by FrankYangIT** [iqiyi/xCrash#70]
xCrash和umeng性能监控不能一起使用，使用之后Xcrash异常监控的回调方法不再回调，目前监控anr就是这样的，注释掉友盟apm正常回调，接入不能回调

**Comment by xuqnqn** [comment]
api 21之后，xcrash ANR 监控是基于ART 发出的SIGQUIT信号，如果这个信号被友盟重复注册回调，那么xcrash在anr发生时是不能正常回调的
