### ISSUE TITLE
tombstone的文件名可以自定义吗？

### ISSUE THREAD

**Issue by wmailn** [iqiyi/xCrash#75]
如题，tombstone的文件名可以自定义吗？或者有解析工具可以通过文件名解析出时间吗？

**Comment by xuqnqn** [comment]
tombstone的文件名不可以自定义，是按照内部定义的文件名固定格式生成的。文件名中有时间戳字段的，可以解析出时间，文件名：tombstone_00001628569507693034_1.2.3-beta456-patch789__xcrash.sample.anr.xcrash

00001628569507693034就是时间戳

**Comment by wmailn** [comment]
有时候需要测试人员手动拷贝出来而不是上传到服务器，这时候测试人员很难分辨出来哪个文件对应当时的崩溃信息，建议增加部分可以自定义文件名或者文件名的时间显示部分可以优化一下…
