### ISSUE TITLE
app发生native crash 日志文件没有写入

### ISSUE THREAD

**Issue by ttsy-80** [iqiyi/xCrash#78]
CrashReport: SIGABRT
    0x57b5
    #00  pc 0003c0a0  /system/lib/libc.so (tgkill+12) [armeabi-v7a::2f8f0a0227b9becf2951b22825df29d8]
    #01  pc 00017a01  /system/lib/libc.so (pthread_kill+52) [armeabi-v7a::2f8f0a0227b9becf2951b22825df29d8]
    #02  pc 00018667  /system/lib/libc.so (raise+10) [armeabi-v7a::2f8f0a0227b9becf2951b22825df29d8]
    #03  pc 00014e27  /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a::2f8f0a0227b9becf2951b22825df29d8]
    #04  pc 0001321c  /system/lib/libc.so (abort+4) [armeabi-v7a::2f8f0a0227b9becf2951b22825df29d8]
    #05  pc 002b4775  /system/app/WebViewGoogle/lib/arm/libwebviewchromium.so [armeabi-v7a::ee3d39903ca8cf9a7ce56dae939f9f71]
    java:
    org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
    android.os.Handler.dispatchMessage(Handler.java:111)
    android.os.Looper.loop(Looper.java:224)
    android.app.ActivityThread.main(ActivityThread.java:5958)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by xuqnqn** [comment]
请描述具体场景，正常情况下xcrash 也支持SIGABRT崩溃日志捕获
