### ISSUE TITLE
ANR发生时callback回调的线程为啥是主线程?

### ISSUE THREAD

**Issue by nangongkuo** [iqiyi/xCrash#80]
ANR发生时callback回调的线程为啥是主线程?我没有看到将回调的线程设置为子线程的方法,因为如果是主线程的话,回调经常接收不到

**Comment by e-snail** [comment]
建议在native层直接启动子线程来回调Java接口  示例如下
`
        JNIEnv *env;
        jboolean isAttached = JNI_FALSE;
        int status = javaVM->GetEnv((void **) &env, JNI_VERSION_1_4);
        if (status < 0) {
            //将当前线程注册到虚拟机中．
            status = javaVM->AttachCurrentThread(&env, NULL);
            if (status < 0) {
                //注册失败
                        return NULL;
                }
            isAttached = JNI_TRUE;
        }

         //回调Java 接口
        env->CallStaticObjectMethod(jobj, <callback id>);


        if (isAttached) {
            javaVM->DetachCurrentThread();
        }

            return NULL;
`

**Comment by shouduzhanshi** [comment]
FileObserver 的回调就是在子线程的，可以看下源码。

**Comment by xuqnqn** [comment]
API 21之前是基于FileObserver ，回调是在子线程的
API 21之后是基于ARG SIGQUIT, 也是使用子线程回调的，子线程名：xcrash_trace_dp
