### ISSUE TITLE
是否提供了写入自定义日志的接口？

### ISSUE THREAD

**Issue by 121880399** [iqiyi/xCrash#83]
由于想在发生Crash或者ANR时插入一些与业务相关的日志，所以想问问xCrash是否提供了将一些自定义日志插入到tomstone文件的接口？

**Comment by xuqnqn** [comment]
请参考demo：
https://github.com/iqiyi/xCrash/blob/1e74a94110aeb0946a181029fd6af35de7061f67/xcrash_sample/src/main/java/xcrash/sample/MyCustomApplication.java#L61
