### ISSUE TITLE
xcrash_sample中ANR (input timeout)触发的ANR，anrCallback没有调用？

### ISSUE THREAD

**Issue by mr-woody** [iqiyi/xCrash#84]
复现操作：
1. 使用xcrash_sample项目，点击MainActivity中的 ANR (input timeout)选项（除这个操作以外的其他操作都能正常触发callback回调，就只是这个操作不行），通过log观察：
`
// callback for java crash, native crash and ANR
        ICrashCallback callback = new ICrashCallback() {
            @Override
            public void onCrash(String logPath, String emergency) {
                //主要看观察这里的日志，查看是否触发？
                Log.d(TAG, "log path: " + (logPath != null ? logPath : "(null)") + ", emergency: " + (emergency != null ? emergency : "(null)"));
`

2.查看xcrash的文件生成情况，发现tombstone_00001626677350096687_1.2.3-beta456-patch789__xcrash.sample.trace.xcrash文件生成成功，但是debug.json文件没有更新，也就是callback没有触发，查看下图所示：
![image](https://user-images.githubusercontent.com/16041337/126115947-d0cbc435-483f-46c9-9f73-631d4f42ec8e.png)

问题：
1. 询问下这种情况应该怎么处理？能使其正常触发callback回调？
2.如果这个问题不能修复？那能否说明下原因？

设备信息：
    "Manufacturer":"OPPO",
    "Tombstone maker":"xCrash 3.0.0",
    "Rooted":"No",
    "pname":"xcrash.sample",
    "Crash time":"2021-07-19T14:09:25.411+0800",
    "OS version":"10",
    "tname":"main ",
    "Brand":"OPPO",
    "Build fingerprint":"OPPO\/PDYM20\/OP4E21:10\/QP1A.190711.020\/1622791319:user\/release-keys",
    "Model":"PDYM20",
    "ABI list":"arm64-v8a,armeabi-v7a,armeabi"

**Comment by xuqnqn** [comment]
OPPO机型都有这个问题，发生ANR时，am.getProcessesInErrorState()返回空。
可以在 XCrash.init时，添加.setAnrCheckProcessState(false)
