### ISSUE TITLE
native.xcrash 文件内容是非文本格式

### ISSUE THREAD

**Issue by liuqingdada** [iqiyi/xCrash#99]
/sdcard/Android/data/xcrash.sample/files/xcrash/tombstone_00001635823546990740_1.2.3-beta456-patch789__xcrash.sample.native.xcrash

<img width="1163" alt="WX20211102-113044@2x" src="https://user-images.githubusercontent.com/15871280/139782566-2bbf97a2-1b5a-483f-9c4e-850a59ec07fd.png">

这种格式的文件具体怎么解析和分析内容

**Comment by DiQinglian** [comment]
后面的看起来像占位符，你是不是配置了占位文件？

**Comment by liuqingdada** [comment]
> 后面的看起来像占位符，你是不是配置了占位文件？

嗯嗯，忘记关了，源码中的逻辑是强行占用存储空间了，全部写进去的 0 应该是。
